"""Every file githood writes, as one flat table of templates.

Placeholders are `{{name}}` rather than str.format fields, so the templates can
contain Python and YAML braces without any escaping games.
"""

from __future__ import annotations

import re

PLACEHOLDER = re.compile(r"\{\{(\w+)\}\}")


def render(template: str, values: dict) -> str:
    def sub(match):
        key = match.group(1)
        if key not in values:
            raise KeyError(f"template asked for unknown value {key!r}")
        return str(values[key])

    return PLACEHOLDER.sub(sub, template)


README = """# {{name}}

Generated by [githood](https://github.com/your-handle/githood) from `{{spec_file}}`.
Every file here is regenerable: change the spec, run githood again.

- broker: **{{broker}}** (paper trading only out of the box)
- symbols: {{symbol_list}}
- timeframe: {{timeframe}}
- risk: max {{max_position_pct}} of equity per position, {{stop_loss_pct}} stop

## Rules

{{rules_md}}

## Run it

```bash
cp .env.example .env      # put your keys here, never in git
make run                  # or: docker compose up
```

## Layout

```
src/broker/    one adapter per venue, all behind the same interface
src/strategy.py  signals in, orders out
src/risk.py      the only file allowed to say no
runs/            receipts from every githood pass, never edited by hand
```

## Safety

The adapters ship in paper mode. `live=True` raises until you implement and
review the order path yourself. Nothing here is financial advice.
"""

GITIGNORE = """.env
.venv/
__pycache__/
*.pyc
runs/*/artifacts/
.DS_Store
"""

ENV_EXAMPLE = """# copy to .env — .env is gitignored
{{broker_upper}}_API_KEY=
{{broker_upper}}_API_SECRET=
GITHOOD_MODE=paper
GITHOOD_CASH={{cash}}
"""

REQUIREMENTS = """# stdlib is enough to start; add what the strategy actually needs
pytest>=8.0
"""

MAKEFILE = """.PHONY: run test lint image ship

run:
\tpython -m src.main

test:
\tpython -m unittest discover -s tests -q

lint:
\tpython -m compileall -q src tests

image:
\tdocker build -t {{slug}}:latest .

ship: test image
\t@echo "image built — push it from CI, not from your laptop"
"""

DOCKERFILE = """FROM python:3.12-slim AS base
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM base AS app
COPY src ./src
ENV PYTHONUNBUFFERED=1 GITHOOD_MODE=paper
CMD ["python", "-m", "src.main"]
"""

COMPOSE = """services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./runs:/app/runs
"""

CI = """name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s tests -q
      - run: docker build -t {{slug}}:ci .
"""

BROKER_BASE = '''"""The interface every venue adapter has to answer."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Quote:
    symbol: str
    price: float


@dataclass
class Order:
    symbol: str
    side: str
    qty: float


class Broker:
    name = "base"

    def __init__(self, live: bool = False):
        if live:
            raise NotImplementedError(
                f"{self.name}: the live order path is yours to write and review"
            )
        self.live = False

    def quote(self, symbol: str) -> Quote:
        raise NotImplementedError

    def submit(self, order: Order) -> str:
        raise NotImplementedError
'''

BROKER_IMPL = '''"""{{broker_title}} adapter — paper mode only.

Fill in the two methods against the real API when you are ready. The base class
refuses to construct in live mode until you have.
"""

from __future__ import annotations

import random

from .base import Broker, Order, Quote


class {{broker_class}}(Broker):
    name = "{{broker}}"

    def quote(self, symbol: str) -> Quote:
        # paper mode: a placeholder price so the loop can be tested end to end
        return Quote(symbol=symbol, price=round(random.uniform(90, 110), 2))

    def submit(self, order: Order) -> str:
        return f"paper-{order.side}-{order.symbol}-{order.qty:g}"
'''

STRATEGY = '''"""Signals in, orders out. The rules from the spec live here."""

from __future__ import annotations

from .broker.base import Order

SYMBOLS = {{symbols_repr}}
TIMEFRAME = "{{timeframe}}"

# rules, straight from the spec:
{{rules_comments}}


def signal(prices: list) -> str:
    """Return "buy", "sell" or "hold" for one symbol's price history."""
    if len(prices) < 50:
        return "hold"
    fast = sum(prices[-20:]) / 20
    slow = sum(prices[-50:]) / 50
    if fast > slow:
        return "buy"
    if fast < slow:
        return "sell"
    return "hold"


def to_order(symbol: str, side: str, qty: float):
    if side == "hold" or qty <= 0:
        return None
    return Order(symbol=symbol, side=side, qty=qty)
'''

RISK = '''"""The only file allowed to say no.

Every number here came from the spec. Change the spec, not this file.
"""

from __future__ import annotations

MAX_POSITION = {{max_position}}   # share of equity in one symbol
STOP_LOSS = {{stop_loss}}         # per-position stop


class RiskError(Exception):
    pass


def position_size(equity: float, price: float) -> float:
    if equity <= 0 or price <= 0:
        raise RiskError("equity and price must both be positive")
    return (equity * MAX_POSITION) / price


def check(equity: float, exposure: float) -> None:
    if exposure > equity * MAX_POSITION:
        raise RiskError(
            f"exposure {exposure:.2f} is over the {MAX_POSITION:.0%} cap"
        )


def stop_price(entry: float, side: str = "buy") -> float:
    return entry * (1 - STOP_LOSS) if side == "buy" else entry * (1 + STOP_LOSS)
'''

MAIN = '''"""One pass of the loop: quote, decide, size, submit — paper by default."""

from __future__ import annotations

import os

from .broker.{{broker}} import {{broker_class}}
from . import risk, strategy


def run_once(equity: float) -> list:
    broker = {{broker_class}}(live=os.getenv("GITHOOD_MODE") == "live")
    filled = []
    for symbol in strategy.SYMBOLS:
        quote = broker.quote(symbol)
        prices = [quote.price] * 50  # replace with real history
        side = strategy.signal(prices)
        qty = risk.position_size(equity, quote.price)
        order = strategy.to_order(symbol, side, qty)
        if order is None:
            continue
        risk.check(equity, order.qty * quote.price)
        filled.append(broker.submit(order))
    return filled


def main() -> None:
    equity = float(os.getenv("GITHOOD_CASH", "{{cash}}"))
    tickets = run_once(equity)
    if not tickets:
        print("no orders this pass — every symbol said hold")
    for ticket in tickets:
        print(ticket)


if __name__ == "__main__":
    main()
'''

TEST_RISK = '''import unittest

from src import risk


class RiskTest(unittest.TestCase):
    def test_size_respects_the_cap(self):
        qty = risk.position_size(equity=10_000, price=100)
        self.assertAlmostEqual(qty, 10_000 * risk.MAX_POSITION / 100)

    def test_over_exposure_raises(self):
        with self.assertRaises(risk.RiskError):
            risk.check(equity=1_000, exposure=999)

    def test_stop_is_below_entry_for_longs(self):
        self.assertLess(risk.stop_price(100, "buy"), 100)


if __name__ == "__main__":
    unittest.main()
'''

INIT = '"""Generated by githood. Edit the spec, not this package."""\n'
